### PR TITLE
Support Guzzle 7 too

### PR DESCRIPTION
**Pull request by ziming**
Hi @s-ichikawa 

Thank you for writing this package.

I hope you will be open to accept this PR to also allow Guzzle 7.

Thank you.

### CODE REVIEW

**Comment by s-ichikawa** [comment]
Cool! Thank you!

**Comment by ziming** [comment]
Thank you. Hope you have a good day.

**Comment by MannikJ** [comment]
Why is this not released yet?

**Comment by s-ichikawa** [comment]
Oh..I forgot it.
Now released as `3.0.2`.
Thank you.

**Pull request merged**
