### PR TITLE
Add sendgrid message id to transport & support laravel 10

### PR DESCRIPTION
**Pull request by parkourben99**
## WHAT
Added X-Sendgird-Message-ID to the header of the email.

## WHY
This was in the previous version for laravel 8. It also provides a way to match emails from incoming webhooks using the message id.

### CODE REVIEW

**Review by tomcodes — APPROVED** [review]
LGTM!

**Review by felipehertzer — APPROVED** [review]
LGTM!

**Comment by parkourben99** [comment]
@s-ichikawa Are you able to review this please.

**Review by s-ichikawa — APPROVED** [review]

**Comment by s-ichikawa** [comment]
@parkourben99 merged! thank you for your contribution!

**Comment by jameswagoner** [comment]
@parkourben99 Curious to know how you utilized the message ID when you are sending mailables.

**Comment by parkourben99** [comment]
> @parkourben99 Curious to know how you utilized the message ID when you are sending mailables.

@jameswagoner You can use this ID to match with the activity webhooks for open, bounce, etc.

**Comment by jameswagoner** [comment]
I'm meant a code example actually. I assume it's by the `SentMessage` event
payload.

I actually submitted my own PR as a result of experimenting. Would
appreciate some holes shot in it.

**Comment by parkourben99** [comment]
Using the SentMessage event taking the `x-sendgrid-message-id` header and matching it with the `sg_message_id` on webhook payloads.

**Pull request merged**
