### PR TITLE
Added reply-to header

### PR DESCRIPTION
**Pull request by eightyfive**
I added the `reply_to` header.

Please consider integrating this fix in a new bug fix version (1.1.x) ?

Thanks,
Ben

### CODE REVIEW

**Comment by s-ichikawa** [comment]
thanks, but would you add test code?

**Comment by eightyfive** [comment]
Do you have a doc explaining what to do and how? Never did that before.

**Comment by s-ichikawa** [comment]
Sorry, the document is not ready.
Please write the code like this in "SendgridV3TransportTest.php".
https://github.com/s-ichikawa/laravel-sendgrid-driver/blob/master/tests/Transport/SendgridV3TransportTest.php#L157-L170

**Comment by eightyfive** [comment]
Ok I just added the test, let me know if that's enough.

**Comment by s-ichikawa** [comment]
Thank you !

**Pull request merged**
